Feature: Inventory

    Scenario: Validate the default app state; sorting option is set to Name A-Z, items are in epxted order with correct properties, and carte is empty
    Scenario: Sorting options work. Can we use a table to represent the 4 sorting options and another table to represent the item? Make sure to have a case for the Add to Catrt and Remove buttons
    Scenario: Add to cart buttons work on various items
    Scenario: Remove buttons work on various items
    Scenario: Reset App State reverts Cart, sorting option, item order, and Remove buttons to default state
    Scenario: I would expect that the sorting order persists when going from one of the cart pages and back to the inventory page.
    Scenario: Removing an item from the Cart also sets item button back to Add to cart
