Feature: Menu Component

# Reset App State behavior is tested in:
# - XYZ.feature
# - ABC.feature

    Scenario: Close button closes the menu
    Scenario: All Items link navigates to the inventory page
    Scenario: About link opens the SauceLabs website
    Scenario: Logout link signs out the current user
    Scenario: Reset App State link restores the default state
    Scenario: Reset App State...I need to idetify all the screems where this needs to be tested. I think it's the inevntory, inventory detail, your cart, and check out overview
