name: Build and test for RestfulBooker.Tests

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'  # Runs at 5:00 AM Eastern during Daylight Saving Time (EDT)
                         # Runs at 4:00 AM Eastern during Standard Time (EST)

jobs:
  build-and-test-restfulbooker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'

    - name: Run build script
      run: pwsh RestfulBooker.Tests/Scripts/build.ps1

    - name: Run test script
      run: pwsh RestfulBooker.Tests/Scripts/test_ci.ps1

    - name: Upload Test Results as Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: TestResults
        path: '**/*.trx'