name: Build and test for SauceDemo.Tests

on:
  pull_request:

jobs:
  build-and-test-saucedemo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'

    - name: Run build script
      run: pwsh SauceDemo.Tests/Scripts/build.ps1

    - name: Run test script
      run: pwsh SauceDemo.Tests/Scripts/test_ci.ps1

    - name: Upload Test Results as Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: TestResults
        path: '**/*.trx'

    - name: Upload Screenshots as Artifact
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: Screenshots
        path: ./SauceDemo.Tests/TestResults/Screenshots
        if-no-files-found: warn